### ISSUE TITLE
[Proposal] Normalisation

### ISSUE THREAD

**Issue by HipsterJazzbo** [thephpleague/url#50]
I'd like to propose adding a normalisation component to this package. Something similar to <https://github.com/glenscott/url-normalizer>.

I've often found that when storing URLs sources from user input especially, it would be very handy to be able to pass in whatever BS and get a normalised, correct (according to <http://www.ietf.org/rfc/rfc3986.txt>) url back out.

I imagine it'd work something like this:

```php
$url = Url::createFromUrl('http://www.example.com/../a/b/../c/./d.html');

$url->normalize(); // Would output something like 'http://www.example.com/a/c/d.html'

echo $url; // __toString() could also normalise by default?
```

Thoughts? I'd be happy to implement something (I'm going to need to write this anyway for my own project), if I was given a bit of guidance as to how you think the best way to go about it would be (perhaps a `NormalizedUrl` class?)

Thanks!

**Comment by HipsterJazzbo** [comment]
Looking into other solutions further, perhaps a port of <https://github.com/PuerkitoBio/purell>?

**Comment by nyamsprod** [comment]
Hi @HipsterJazzbo I've been thinking about the same kind of property for a while but I did not have the time to properly look into it. A proper way to add this would be to add the ability to the League\Url\Interfaces\PathInterface

**Comment by HipsterJazzbo** [comment]
I'm not sure that *would* be the right place. There are normalisations that apply to all parts of the url. For example:

1. Converting the scheme and host to lower case
2. Capitalizing letters in escape sequences
3. Decoding percent-encoded octets of unreserved characters
4. Adding trailing /
5. Removing the default port
6. Removing dot-segments

There are many others that are possible, and none are that hard to support, it's more a question of offering them as optional to the developer because some can change the semantics of the URL.

For this reason I like the Flag approach of Go's [Purell](https://github.com/PuerkitoBio/purell), although bitwise operators can be confusing to some programmers.

**Comment by nyamsprod** [comment]
Sorry I didn't read fully your argument I just look at your code example and responded to it.
First let's keep in my that they are [several normalizations that can be applied to URLs](http://en.wikipedia.org/wiki/URL_normalization) some always preserve semantics others don't. 

I would argue that those that preserve semantics if incorporated into the package may be added without changing the public API as it forces a clean and better representation of the URLs.

The others normalizations **may** be added to the package only through the use of a dedicated method into the corresponding component. Having said that, let me recap your propositions:

> 1.Converting the scheme and host to lower case

**preserve semantics** This is already the case for the scheme component. A PR could be done to force the same behavior onto the host component without changing the current API.

> 2.Capitalizing letters in escape sequences
> 3.Decoding percent-encoded octets of unreserved characters

**preserve semantics**  A PR could be done to add these behaviors without changing the current API.

> 4. Adding trailing /

**don't preserve semantics** This one is so controversial that I won't even go down that road [references for bibliography](https://github.com/nicolaiarocci/eve/issues/118). To remain free of futures issues I won't accept any PR that add the "missing" trailing `/`

> 5.Removing the default port

**preserve semantics**  The default port depends on the scheme. If in future versions we open the scheme component to other schemes, we will have to keep track of each possible default port. Since nothing in the current API prevents you from removing the port value if it is unnecessary. The gain versus the tradeoff is not that significant to require this feature to be added.

> 6. Removing dot-segments

**don't preserve semantics** This method is what I was talking about and this belongs to the  `PathInterface` IMHO. This should be done using a distinctive method which returns a new `PathInterface` object as it may modify the meaning of the path in some environment.

**Comment by nyamsprod** [comment]
I've just push a [commit](https://github.com/thephpleague/url/commit/86795ebeb9cc4bcdbe97c428e563926a66231015) to the master branch which covers:

> 1.Converting the scheme and host to lower case
> 2.Capitalizing letters in escape sequences
> 3.Decoding percent-encoded octets of unreserved characters

Without changing the public API

>  6.Removing dot-segments 

Through the addition of the `PathInterface::normalize` method. Any other normalization can be done through composition IMHO.

**Beware** when using the master branch as it introduces many BC breaks from v3.
