### ISSUE TITLE
Adding a scheme to a schemaless url makes it invalid

### ISSUE THREAD

**Issue by ArtemGordinsky** [thephpleague/url#88]
Hi,
I'm not sure if what I'm doing is correct, but I'm unable to get a valid url using the following piece of code:

```php
$url = \League\Url\Url::createFromUrl('google.com');

if (!$url->getScheme()) {
	$url = $url->withScheme('http');
}

echo $url; // 'http:google.com'; expected 'http://google.com'
```

Am I doing something wrong?
Using version 4.0.0-beta.3.

**Comment by nyamsprod** [comment]
Hi @ArtemGordinsky 

This is not a bug but the expected behavior
```php
 $url = \League\Url\Url::createFromUrl('google.com');
$url->toArray(); // will display
 // [
 //     'scheme' => null,
 //     'user' => null,
 //     'pass' => null,
 //     'port' => null,
 //     'path' => 'google.com',
 //     'query' => null,
 //     'fragment' => null,
 // ]
```
So you did not provide a **host** but only a **path**. 

The next line also is expected behavior since you set up a scheme you end up with a scheme and an path only URI. Now this opens a issue in PSR-7 (see https://github.com/zendframework/zend-diactoros/issues/65). This issue is not yet resolved with an errata.

In the meantime, the current package has been updated to return a RuntimeException in such case. The updated package can be found at https://github.com/thephpleague/uri has this will be the new repo for v4. The move was made to avoid dependency hell.

**Comment by ArtemGordinsky** [comment]
Understood, thanks for the explanation!
