### ISSUE TITLE
[3.x] sanitization limits available schemes

### ISSUE THREAD

**Issue by rpnzl** [thephpleague/url#89]
I ran into some issues in an attempt to use this library to manipulate URLs with schemes outside of `http(s)`, `ftp`, and `ws(s)`. The limited scope seems to originate in [`AbstractUrl::sanitizeUrl()`](https://github.com/thephpleague/url/blob/3.x/src/AbstractUrl.php#L271), specifically the RegExp `^((http|ftp|ws)s?:)`.

I did some searching and couldn't find any discussion on this topic, but I commonly use URLs to locate a variety of other resources that my applications consume (MySQL, Redis, etc.). It looks like the 4.x release uses a scheme registry to allow for extensions to the main set of schemes and provide full [RFC 3986](http://tools.ietf.org/html/rfc3986) compliancy -- I understand that accounting for all of these can become unwieldy as a RegExp in the 3.x branch, but is it worth putting together a PR to include some other common schemes?

Let me know if I missed some discussion on this somewhere, if so, apologies! Thanks.

**Comment by nyamsprod** [comment]
Hi @rpnzl  thanks for using the league\Url package. The limitation in v3 is done because if you read RFC3986 URI parsing you'll notice that each URI (ftp, ws, http, data, mailto, etc...) using its own parsing algorithm. trying to unify them under one class is impossible.
When developing v4 I started by adding more schemes but it adds more bugs. That's why to enable more schemes a different approach is taken in v4. So the problem is not the regex on itself but the consequences of adding more schemes.
Last but not least League\Url v4 development has been move to another repo https://github.com/thephpleague/uri to avoid dependency hell. So you should look at this repo for more information

**Comment by rpnzl** [comment]
Hey @nyamsprod, thanks for the response and clarification -- looking forward to v4!
