### ISSUE TITLE
League\Interfaces\Component\Query + ArrayAccess

### ISSUE THREAD

**Issue by shabbyrobe** [thephpleague/url#90]
It would be great if the Query interface could support the `ArrayAccess` interface, which would allow `$url->query['pants']`:

```
interface Query extends Collection, Component, ArrayAccess
```

You can then raise a `BadMethodCallException` when `offsetSet` or `offsetUnset` are called for immutability.

**Comment by shabbyrobe** [comment]
I had a better look at this and whipped up a version on my own fork: https://github.com/shabbyrobe/url/tree/arrayaccess

I don't know whether it's worth merging or not, I just prefer the array notation as less verbose and less visually noisy, particularly when there are a lot of values to be extracted from a query. Please let me know if it's worth submitting (pending any cleanup) or if I should close it off.

**Comment by nyamsprod** [comment]
HI @shabbyrobe,
The package new version is now developped on  https://github.com/thephpleague/uri to avoid dependency hell and for better clarity.
That being said..I'm a little on the fence for adding the ArrayAccess interface to the QueryInterface. Because users may think the Query will return the same data has PHP's `parse_str` which is not true. in v4 the Query returns the key pairs so for instance using the following code would be unintuitive:

```php
$query = new Query('foo[bar]=1&foo[baz]=2');
$query->getValue('foo'); // will return null
$query->getValue('foo[bar]'); //will return 1
$query['foo']; //people would assume ['bar' => 1, 'baz' => 2];
```
I may be wrong about it but this is what I think ? What do you think ?
This is the same reasoning behind not implementing the ArrayAccess Interface for the Host object for instance

**Comment by nyamsprod** [comment]
ArrayAccess has been added to the  https://github.com/thephpleague/uri package
